# Generated by Django 3.1.1 on 2020-09-21 22:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filter_order', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField()),
                ('title_order', models.IntegerField(default=-1)),
                ('is_related', models.BooleanField(default=False)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('int_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('date_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.attribute')),
                ('related_values', models.ManyToManyField(blank=True, related_name='_attributevalue_related_values_+', to='posts.AttributeValue')),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(blank=True, db_index=True, default=datetime.datetime.now)),
                ('updated', models.DateField(blank=True, db_index=True, default=datetime.datetime.now)),
                ('slug', models.SlugField(blank='True', max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('price', models.PositiveIntegerField(blank=True, db_index=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone3', models.CharField(blank=True, max_length=10, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('attributes', models.ManyToManyField(to='posts.AttributeValue')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('commune', models.ManyToManyField(to='regions.Commune')),
                ('motif', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='posts.motif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
