# Generated by Django 3.1.1 on 2020-09-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='post',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='telephone2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='telephone3',
        ),
        migrations.AlterField(
            model_name='post',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='posts.AttributeValue'),
        ),
    ]
