# Generated by Django 3.1.1 on 2020-09-27 14:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200921_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promotional',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(db_index=True),
        ),
    ]
