# Generated by Django 3.1.1 on 2020-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200927_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='posts.AttributeValue'),
        ),
    ]
