# Generated by Django 3.1.1 on 2020-09-28 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200927_1409'),
        ('posts', '0004_auto_20200927_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livraison', models.PositiveIntegerField(default=0)),
                ('post', models.ManyToManyField(to='posts.Post')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.wilaya')),
            ],
        ),
    ]
