# Generated by Django 3.1.1 on 2020-09-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postlivraison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlivraison',
            old_name='post',
            new_name='posts',
        ),
    ]
