# Generated by Django 3.1.1 on 2020-11-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200928_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='promotional',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
