# Generated by Django 3.1.1 on 2020-09-21 22:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=10, null='True')),
                ('adresse', models.CharField(default='alger', max_length=325)),
                ('activate', models.CharField(max_length=255, unique='True')),
                ('solde', models.IntegerField(default=0)),
                ('rolee', models.CharField(choices=[('Client', 'Client'), ('Vendeur', 'Vendeur'), ('Blogeur', 'Blogeur')], default='Client', max_length=255)),
                ('commune', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='regions.commune')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank='True', default=datetime.datetime.now)),
                ('montant', models.PositiveIntegerField()),
                ('observation', models.TextField(null='True')),
                ('user', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePayement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank='True', default=datetime.datetime.now)),
                ('montant', models.PositiveIntegerField()),
                ('methode', models.CharField(choices=[('Virement ccp', 'Virement ccp'), ('Virement Bancaire', 'Virement Bancaire'), ('Cash', 'Cash')], max_length=255)),
                ('message', models.TextField(blank='True', null='True')),
                ('user', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
