# Generated by Django 3.1.1 on 2020-11-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201106_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoussession',
            name='session',
            field=models.CharField(default='cb65675b80af9970adeeef6537caec5c', max_length=255, unique=True),
        ),
    ]
