# Generated by Django 3.1.1 on 2020-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201115_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoussession',
            name='session',
            field=models.CharField(default='5262dbd98b44833bbc1ab2112ff6138b', max_length=255, unique=True),
        ),
    ]
