# Generated by Django 3.1.1 on 2020-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200927_2217'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='posts.Attribute'),
        ),
    ]
