# Generated by Django 3.1.1 on 2020-09-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='prix',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
