# Generated by Django 3.1.1 on 2020-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_commune_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='prix',
        ),
        migrations.AddField(
            model_name='wilaya',
            name='prix',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
