# Generated by Django 3.1.1 on 2020-10-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='produit',
            new_name='post',
        ),
    ]
