# Generated by Django 3.1.1 on 2020-11-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200928_2212'),
        ('cart', '0003_auto_20201006_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='attributevalue',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='attributevalues',
            field=models.ManyToManyField(blank=True, null=True, to='posts.AttributeValue'),
        ),
    ]
