# Generated by Django 3.1.1 on 2020-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200928_2212'),
        ('cart', '0004_auto_20201105_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='attributevalues',
            field=models.ManyToManyField(blank=True, to='posts.AttributeValue'),
        ),
    ]
